### ISSUE TITLE
How do we make the jar file?

### ISSUE THREAD

**Issue by MattTree** [Dylancyclone/VMF2OBJ#12]
To the users or developers out there, how were you able to make the Jar file?

I followed the tutorial below but I'm missing something:

```
 - Start Command Prompt.

 - Navigate to the folder that holds your class files:

    C:\>cd \mywork

 - Set path to include JDK’s bin.  For example:

    C:\mywork> path c:\Program Files\Java\jdk1.7.0_25\bin;%path%

 - Compile your class(es):

    C:\mywork> javac *.java

 - Create a manifest file

   manifest.txt with, for example, this content:

        Manifest-Version: 1.0
        Created-By: 1.8.0_171 (Oracle Corporation) #your jdk version
        Main-Class: mainPackage.MainClass

 - Create the jar file:

    C:\mywork> jar cvfm Craps.jar manifest.txt *.class
```
([tutorial link](https://stackoverflow.com/a/19650753/3822261))

However I can't get past the create-classes step:

When I type:

`javac .\src\main\java\com\lathrum\VMF2OBJ\*.java`

I get 100 errors:

![image](https://user-images.githubusercontent.com/68766223/88979184-c9202880-d286-11ea-8e47-2138f5093420.png)

Thank you for your time.

**Comment by Dylancyclone** [comment]
Hello!
This project uses a build tool called [Maven](https://maven.apache.org/) that handles compiling. Once you have it downloaded and installed, you should be able to compile the project into a jar file with: `mvn package`.

Maven is used to help make the build process easier (just one short command that handles compiling and packaging into a jar file), and to help with dependencies

Let me know if that works!

**Comment by Dylancyclone** [comment]
Are you still having this issue @MattTree ? If not, I'll close the issue

**Comment by MattTree** [comment]
After being stuck I found different software to convert to OBJ. Thanks for your attention. Hopefully someone else who was stuck like me will be able to use the solution you provided.
