### ISSUE TITLE
Missing faces, misaligned terrain, flipped normals

### ISSUE THREAD

**Issue by Auburn** [Dylancyclone/VMF2OBJ#16]
Hi, I've been trying to convert de_dust2 from CS:GO and have run into a few issues. (Converted using -t)

- Small sections of walls are missing throughout the map, it looks like some faces weren't exported
- The floor (terrain) has a large number of missing/misaligned sections, it appears to affect sloped area the worst

![image](https://user-images.githubusercontent.com/1349548/104327148-5f1cd800-54e2-11eb-9e48-ed53be758e6e.png)
 
- In the exported mesh the map (floor & some walls) seem to have inverted normals, the props all have correct normals

![image](https://user-images.githubusercontent.com/1349548/104327723-fe41cf80-54e2-11eb-8dfd-64341c087610.png)

Dark areas show backfaces in the mesh

Thanks for this great tool!

**Comment by Dylancyclone** [comment]
Hello!
Sorry about the delay, and thank you, think helped me track down the issue with the brushes. I've pushed a fix (the commit above) that'll be a part of the next release, and I'll start looking into the displacements. Unfortunately, I thought I fixed those already, but it seems like the fix doesn't work everywhere.
