### ISSUE TITLE
Wont open

### ISSUE THREAD

**Issue by pontusedberg** [Dylancyclone/VMF2OBJ#21]
Heya, i might be just stupid, but how do i actually run this java extension?
Double clicking on it does nothing, do i need some kind of program to run it other than java?
lots of love

**Comment by GrayCatTheMemeMachine** [comment]
You need to run it on a command line (cmd, Or Windows PowerShell), This doesn't really have much of an interface.
At around [2:30](https://youtu.be/3CgoCSRIGqI?t=150) on this [video,](https://youtu.be/3CgoCSRIGqI) (Along with a complete explanation at [2:00](https://youtu.be/3CgoCSRIGqI?t=120)). You can see him using the command line.
Notice how he opens it with right-click and clicks (Open With Windows PowerShell). He also explains and shows the general locations you might need, Along with the commands.

If you don't know much about the Mapping Files/VPK files for Source Games In general, (Or how to use it in Blender)There are lots of other places to learn. I'm willing to give some info from my own experience if ya want, Not the best all things considered tho.

**Comment by Dylancyclone** [comment]
@GrayCatTheMemeMachine is right! (thank you!)

I have also been working on a GUI as well, and have just put up a pre-release version that has it while I hammer out a couple more things: https://github.com/Dylancyclone/VMF2OBJ/releases/tag/2.0.0-rc.1

If you'd like to try it out, you can [download it](https://github.com/Dylancyclone/VMF2OBJ/releases/download/2.0.0-rc.1/VMF2OBJ-2.0.0-rc.1.jar) and double click on it to bring up a friendlier interface, or you could run
```
java -jar ./vmf2obj-2.0.0-rc.1.jar --help
```
 in your terminal to bring up the original command-line interface.

Let me know if that helps, or if you have any other questions/issues!
