### ISSUE TITLE
Rotation Of Map Not Being Right + Displacement Orientation Not Right

### ISSUE THREAD

**Issue by GrayCatTheMemeMachine** [Dylancyclone/VMF2OBJ#22]
### Main Info
I exported a custom map of mine, It manages to come out on its side (On its _Y-Axis_). The Models and Materials came out okay though. I exported an HL2 Background Map to see the same thing was happening. I wouldn't really consider this an issue because I can flip it manually, But a different issue arises. "_Displacement Rotation/Orientation Not Right_". The displacements become jumbled when it comes to how it rotated on its Z-Axis. They were exported almost perfectly, With the main problem being the rotation. The whole structure of the map was built around the displacements and the way it curved to make a walkable path when everything was aligned correctly. May also be the displacements not actually exporting right in general.

_Displacements and some misc map info need some work when it comes to how they export. I know you've still been trying to tackle these weird issues so I hope you can maybe use this info._

### Extra Debug Info

- My Displacements were really complex. _(This probably meant there was alot of displaced geometry, And alot of chances to trip up)_
- Used Portal 1's Hammer (.Exe From The Bin) To create the Source VMF Used for the OBJ. _(Doubt Portal 1's Hammer works differently enough from all the others to really cause a problem on its own. Each game has its quirks though, So IDK)_
- Used 1 Custom Model _(It worked on the OBJ File, The rotation of this model, Which was a train/tram remake from HL2, Was rotated around the displacements. It was rotated right too, Just that the displacements weren't)_
- Used **VMF2OBJ-2.0.0-rc.1** _(I know you're testing this one out, Have no idea if the changes from the version previous are the problem here)_
- The map had all of the displacements put into the preferred position _(Can't recall if I did any changes to rotation in hammer though. Might be rotation editing in Hammer doesn't get translated into the OBJ?)_
- Log appeared successful (No errors, No missing assets. The UI Said everything exported alright)
- Map Name: "c1_hp1cutscene" _(I know some special characters can wack things, Just wanted to show the name just in case)_
- What it looks like when first loaded in Blender (This is the right camera position too, Turned grid off but this is the right view)
![Exmp1](https://user-images.githubusercontent.com/77712883/127655695-4fefa492-db28-49e2-b559-01bd63e44d8d.JPG)
- What it looks like when flipped to right rotation (You should be able to go to point A- To point B without any obstruction, Along with the hills stopping you from falling off)
![Exmp2](https://user-images.githubusercontent.com/77712883/127655876-06a4ca95-8bbd-4128-89a8-0fe501a41a5f.JPG)
- What it looks like in Hammer properly (The angle showed here makes one cutoff to the fence look like it could have a wall but it actually doesn't in the editor)
![Exmp3](https://user-images.githubusercontent.com/77712883/127656115-9e8ccdc1-ff2b-4e0f-a788-afe280f02e0a.JPG)

### End Message (Thing-)

This isn't the worst issue, All things considered, I'm hella impressed it worked good as it did. I'll be honest and say I'm pretty dumb, If I'm just spitting out blank info- Please point me in the right direction. All of these can be tweaked manually at least. In the meantime, I'll optimize the displacements in Hammer and or Blender to hopefully get the map I want ready for some animation work. I'm really weirded out by this, But I can hope you can maybe optimize the program.

I'm also willing to give more info, And or debug some things if ya want

**Comment by Dylancyclone** [comment]
Hi!
> I exported a custom map of mine, It manages to come out on its side (On its Y-Axis).

This is actually kinda intended. Even though both Blender and Hammer use the Z-Axis as "up," when importing a .obj file in Blender it defaults to the Y-Axis being "up" for some reason (one thing that comes to mind is other engines like Unity use the Y-Axis as up, but I don't really know so don't quote me on that).

![image](https://user-images.githubusercontent.com/19830705/127717763-69d7e202-07b8-4898-8dc8-f53de3a7111b.png)

You can either change it in the import menu above, or reset the rotation after the .obj is imported

![image](https://user-images.githubusercontent.com/19830705/127718087-39eef954-031f-4294-977d-804d926f2b30.png)


> The displacements become jumbled

Yep, that's the last thing I'm really trying to figure out before releasing the new version. Some times it works just fine, other times it looks completely broken like in the pictures you've posted. I'm still trying to track down the cause of the problem, I just haven't had an abundance of time recently to really dig into it.

> Displacements and **_some misc map info_** need some work when it comes to how they export.

I agree with the displacements, but what do you mean with "misc map info"?

Thank you for all the additional information, it really helps track down where the problem is coming from!

**Comment by GrayCatTheMemeMachine** [comment]
I mostly meant "Misc Map Info" As some of the extra clips or tags used for Source (Map Tags, Point Objects - Like Lighting, Tool Brushes/Textures).

At the moment I do know some tool and tool textures just refuse to really work (At least in the way Source reads them, Blender it either breaks the map a bit or just renders the label onto objects), But to be fair they were only really meant for Source to read. 

The only real tool texture that would be nice to have worked as an export would be the skybox? I have no idea how hard it'll be for VMF2OBJ To read the skybox tool texture into a skybox cube or other shape, Definitely do know if it can read and find the skybox files and just export them that'll be already pretty useful. 

For things like baking lighting, That kinda sounds like a nightmare, Don't really know if that's possible.

But yea this is all I meant by that, Thank you, and good luck developing! (And having the patience to work with both Hammer and Source for long periods of time-)
