### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by Devostated** [Dylancyclone/VMF2OBJ#23]
I got the following error while trying to convert a de_Dust2 CSGO map.

Processing entities...  16% [=>          ]  603/3751 (0:00:01 / 0:00:05) 603.0/sSEVERE: Fatal error: java.nio.file.NoSuchFileException: C:\Users\Devo\AppData\Local\Temp\vmf2objtemp\models\props\autocombine\de_dust2\dust_window_frame_.smd

The tool did create a folder called autocombine, while the VMF uses the path autocombine2.
dust_window_frame_.smd is also a weird name, there shouldn't be any file called like that since there is a missing word after the frame_.

**Comment by Dylancyclone** [comment]
Hello!
I am unable to reproduce this locally, when I try to convert de_dust2 the conversion succeeds without any errors. I agree, `dust_window_frame_.smd` is a weird name and it should have something after the last underscore, as I'm seeing here:
![image](https://user-images.githubusercontent.com/19830705/127789340-3276b1d8-4bc1-4f65-b105-1f67ff87d74f.png)


https://github.com/Dylancyclone/VMF2OBJ/releases/tag/2.0.0-rc.2

**Comment by Devostated** [comment]
Same error:
Processing entities...   0% [>               ]   29/3751 (0:00:00 / 0:00:00) ?/sSEVERE: Fatal error: java.nio.file.NoSuchFileException: C:\Users\Devo\AppData\Local\Temp\vmf2objtemp\models\props\autocombine\de_dust2\dust_window_frame_.smd

Processing entities...  16% [=>          ]  603/3751 (0:00:01 / 0:00:05) 603.0/s

I will try and decompile again.
