### ISSUE TITLE
Several errors while converting decompiled maps from Portal 2

### ISSUE THREAD

**Issue by irishgreencitrus** [Dylancyclone/VMF2OBJ#25]
Not sure what happened here. I've decompiled all the maps from portal 2 using bspsrc and have had moderate success however things keep cropping up and one in particular is really annoying due to it failing to give me any output at all.
These errors include:
```
SEVERE: Fatal error: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 2564665 path $.entities[414].ACH.A3_DOORS"[6]
```
When i'm converting `sp_a3_transition01.bsp` as well as several errors in other maps like
```
Failed to parse Material: nature/water_bottomless_pit_01
Missing Material: concrete/concrete_bts_ceiling001a_noportal
Failed to parse Material: plastic/plasticwall001b
Prop has no model? prop_testchamber_door
Failed to parse Material: circle_shield_main
```
It's more likely to be my fault than the tools however i'm not really sure how to solve any of these. If anyone else has encountered these and fixed them please let me know how.

**Comment by asd417** [comment]
Hi I tried this new version as I was also experiencing errors like the ones op experienced. 
I get this message when starting the program
`SEVERE: Failed to extract tools, do you have permissions?
SEVERE: java.io.FileNotFoundException: D:\Documents\Git\VMF2OBJ\target\VMF2OBJ-2.0.0-rc.2-jar-with-dependencies.jar (지정된 경로를 찾을 수 없습니다)
Starting VMF2OBJ conversion v2.0.0-rc.2
[1/5] Reading VPK file(s) and custom content...
[2/5] Reading geometry...`
The korean message translates to 'can not find directory'

**Comment by asd417** [comment]
Also noticed that when attempting to set output file to an existing output file, the process gets interrupted like this:

```

Failed to parse Material: effects/fizzler_center
Failed to parse Material: effects/fizzler_center
Failed to parse Material: effects/fizzler_l
Failed to parse Material: effects/fizzler_center
Failed to parse Material: effects/fizzler_r
Failed to parse Material: effects/fizzler_center
Writing Brushes... 100% [=========================================================] 490/490 (0:00:22 / 0:00:00) 22.3/s
[4/5] Processing entities...
Material has no texture: glasswindow_observation
Prop has no model? prop_testchamber_door
Material has no texture: glasswindow_observation
Processing entities...  25% [=============>                                        ]  72/282 (0:00:19 / 0:00:55) 3.8/sException in thread "main" java.io.IOException: Cannot run program "C:\Users\locti\AppData\Local\Temp\vmf2objtemp\CrowbarCommandLineDecomp.exe": CreateProcess error=2, 지정된 파일을 찾을 수 없습니다
        at java.lang.ProcessBuilder.start(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at com.lathrum.VMF2OBJ.App.main(App.java:978)
Caused by: java.io.IOException: CreateProcess error=2, 지정된 파일을 찾을 수 없습니다
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        ... 4 more
Processing entities...  25% [=============>                                        ]  73/282 (0:02:06 / 0:06:01) 0.6/s

```

**Comment by Dylancyclone** [comment]
Hi! Could you please try out the newest version? https://github.com/Dylancyclone/VMF2OBJ/releases/tag/2.0.0-rc.3
Let me know if that works for you
