### ISSUE TITLE
Error while decompiled maps from Portal 2

### ISSUE THREAD

**Issue by iberians** [Dylancyclone/VMF2OBJ#27]
The map is [Chapter 6 Beyond the Seal](https://theportalwiki.com/wiki/Portal_2_Chapter_6_Beyond_the_Seal), .bsp file is sp_a3_03
The errors that appear in the _progress_
```
[info] Unequal amount of areaporal entities and areaportal brushes. Falling back to 'Manual' method
[info] No occluders to reallocate...
[warning] EntitySource: funct_areaportal entity links to a non existing areaportal, skipping...
```
And error that appear in _Errors & Warnings_
```
[warning] EntitySource: funct_areaportal entity links to a non existing areaportal, skipping...
```

**Comment by Dylancyclone** [comment]
Hello!
Are you getting those warnings/errors while using VMF2OBJ or while decompiling the map using bspsrc? Those look like bspsrc errors
