### ISSUE TITLE
-e argument prevents program from running

### ISSUE THREAD

**Issue by CheezusChrust** [Dylancyclone/VMF2OBJ#29]
If I try to add an external content path (tried both a folder containing materials/models/etc. and the materials folder itself) the program simply displays the help menu without any errors.

**Comment by Dylancyclone** [comment]
Hi! What is the full command you are using to run the program?

**Comment by CheezusChrust** [comment]
Whoops, forgot to include that
`java -jar .\VMF2OBJ-1.1.3.jar .\input.vmf .\output "B:\SteamLibrary\steamapps\common\Half-Life 2\hl2\hl2_textures_dir.vpk;B:\SteamLibrary\steamapps\common\Half-Life 2\hl2\hl2_misc_dir.vpk" -e "B:\User Data\Games\Mapping\Episode 2\" -t`

**Comment by Cyzzle-Belle** [comment]
If it helps, I am able to recreate the issue. When I run it through the GUI, I am getting a `SEVERE: Fatal error: java.lang.StringIndexOutOfBoundsException: String index out of range: -1`. Not sure why this is not being shown in the CLI.

I am on crappy internet so I do not have the JDK and cannot dig deeper at this time. Hope this might help.

**Comment by Dylancyclone** [comment]
Hello! With the rework to how external content is handled in version 2.0.0, this issue should be fixed. If you are still having problems please feel free to reopen or create a new issue!
