### ISSUE TITLE
Collapse *almost* duplicate vertices

### ISSUE THREAD

**Issue by Dylancyclone** [Dylancyclone/VMF2OBJ#3]
Similar to #1 and #2, but with a margin of error. The program already merges vertices if they are exact duplicates of each other, but for more complicated geometry there could be rounding errors that make the vertices technically slightly different, but effectively the same. It would be a good optimization and improvement if the extra vertices were merged together. The struggle with this is making sure any faces that use the collapsed vertex texture are redirected to the one that was kept.

**Comment by TheBlizWiz** [comment]
It might be useful to do a Merge by Distance operation and then set the tolerance to as large as it would need to be to merge all of the almost exact vertexes. You'd have to be careful that a prop isn't going to merge with a brush face, though.
