### ISSUE TITLE
SEVERE: Fatal error: [...] Unterminated object at line 1 column 1554 path $.solids[0].sides[0].null

### ISSUE THREAD

**Issue by TadzTadz** [Dylancyclone/VMF2OBJ#36]
Log:

Starting VMF2OBJ conversion v2.0.0
[1/5] Reading VPK file(s) and custom content...
[2/5] Reading geometry...
SEVERE: Fatal error: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 1554 path $.solids[0].sides[0].null

**Comment by Dylancyclone** [comment]
Hi, what map are you trying to decompile?

**Comment by TadzTadz** [comment]
a .vmf containing a simple world brush

**Comment by TadzTadz** [comment]
I think I just found the source of the problem,
.vfm files from Hammer++ cause the error, while files from the standard csgoSDK dont have this proble
[SEVERE Fatal error.zip](https://github.com/Dylancyclone/VMF2OBJ/files/8955811/SEVERE.Fatal.error.zip)
m
