### ISSUE TITLE
Fatal Error on the reading geometry step

### ISSUE THREAD

**Issue by Boneless-Sans** [Dylancyclone/VMF2OBJ#37]
"SEVERE: Fatal error: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 42084 path $.solids[0].sides[0].null"

**Comment by Dylancyclone** [comment]
Hiya, what map are you trying to convert?

**Comment by Dylancyclone** [comment]
Hi I'm going to close this since I don't have enough information to investigate further. Feel free to respond or create a new issue if you're still having trouble.
