### ISSUE TITLE
can't run, tried solutions listed in other issues, did not work

### ISSUE THREAD

**Issue by wierdowilli** [Dylancyclone/VMF2OBJ#38]
I have Java installed, but running the GUI version of the .jar file just does nothing. Is there anything I can do to fix?

**Comment by Dylancyclone** [comment]
If you try to launch it through the command line (even just the help command `java -jar ./VMF2OBJ.jar --help`), does it give you any additional information?

**Comment by Dylancyclone** [comment]
Hi I'm going to close this since I don't have enough information to investigate further. Feel free to respond or create a new issue if you're still having trouble.
