### ISSUE TITLE
Texture UVs appear to be flipped

### ISSUE THREAD

**Issue by WolfieWaffle** [Dylancyclone/VMF2OBJ#40]
Not sure exactly what's going on. All I know is I made a test map to demonstrate this: I set these sloped textures as you can see, then exported it to obj, then when I open in blender they are flipped. 
![image](https://user-images.githubusercontent.com/8770485/213367145-44782e07-53cc-4806-b625-7d3a115e360d.png)
![image](https://user-images.githubusercontent.com/8770485/213367178-004bafd5-a205-4238-a9e2-f0e732980bb5.png)
this also appears to happen in windows 10 object viewer so I don't think it's Blender

**Comment by Dylancyclone** [comment]
Hi! Could you please upload the map you're testing with so I could take a closer look?

**Comment by Dylancyclone** [comment]
Hi I'm going to close this since I don't have enough information to investigate further. Feel free to respond or create a new issue if you're still having trouble.
