### ISSUE TITLE
Trouble using custom materials/models

### ISSUE THREAD

**Issue by DragonsHidden** [Dylancyclone/VMF2OBJ#44]
I am confused on how you import custom materials and models without VPK. As it seems its possible based on your writing in the description. Yet i cannot figure it out. Am I missing something key?

**Comment by Dylancyclone** [comment]
I'm so sorry about the delay, I definitely thought I responded to this issue

To use external resources that are not in a VPK file, you can directly add the path to the folder that contains the "models"/"materials" folders.

```
custom-content/        <----- Select this folder
├── materials/         <----- DON'T select this folder
│   └── models/
│       └── props/
│           ├── clock.vmt
│           └── clock.vtf
└── models/            <----- DON'T select this folder
    └── props/
        ├── clock.dx80.vtx
        ├── clock.dx90.vtx
        ├── clock.mdl
        ├── clock.phy
        ├── clock.sw.vtx
        └── clock.vvd
```

I have added this to the readme, thank you for pointing out the confusion!
