### ISSUE TITLE
SEVERE: Error while loading vpk file: Invalid signature

### ISSUE THREAD

**Issue by Tooop22** [Dylancyclone/VMF2OBJ#45]
I get this error when trying to convert
![Capture](https://user-images.githubusercontent.com/128878655/235298972-bb65d4dc-e470-4985-99ff-e29cbf5b4d18.PNG)

**Comment by DoritoTheChips** [comment]
Do not use the `garrysmod_xxx.vpk` files, only use the `garrysmod_dir.vpk` files.

**Comment by Dylancyclone** [comment]
Hi I'm going to close this since I'm guessing the issue is resolved. Feel free to respond or create a new issue if you're still having trouble.
