### ISSUE TITLE
Severe fatal error

### ISSUE THREAD

**Issue by Lazymonk1921** [Dylancyclone/VMF2OBJ#46]
When im trying to convert a custom map that i made into obj i get this error

SEVERE: Fatal error: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 1626 path $.solids[0].sides[0].null

Im using hl2_textures_dir, hl2_pak_dir and hl2_misc_dir vpks. 

Any help pls?

**Comment by Lazymonk1921** [comment]
![Screenshot_1](https://github.com/Dylancyclone/VMF2OBJ/assets/59169411/3df25398-e43d-4bfa-8a1e-ac689b202b1e)

Here is how this looks

**Comment by Lazymonk1921** [comment]
Im using hammer++ could that be the issue?

**Comment by Lazymonk1921** [comment]
Hilfe bitte?

**Comment by VictorMolokanov** [comment]
i give this error awesome.

**Comment by Dylancyclone** [comment]
Hello!
Sorry about the long delay, life reared it's ugly head for a bit.

Is it possible to link the map you're converting? It might be an issue relating to Hammer++, that error leads me to believe the vmf file might be formatted differently

**Comment by Dylancyclone** [comment]
Hi, I've released an update that fixes the error when trying to decompile any VMF file saved in Hammer++ https://github.com/Dylancyclone/VMF2OBJ/releases/tag/v2.0.1

I'm going to close this as the original issue is fixed, though definitely let me know if you have any other issues!
