### ISSUE TITLE
Could not find QC file for model (Map from Portal 1)

### ISSUE THREAD

**Issue by RetroAndDev** [Dylancyclone/VMF2OBJ#47]
Hello,
I try to convert the 'testchmb_a_00_d.vmf' file from Portal 1.
I'm on v2.0 on macOS.
Here's a capture of the home tool
<img width="1004" alt="Capture d’écran 2023-08-16 à 23 17 30" src="https://github.com/Dylancyclone/VMF2OBJ/assets/56597499/cb1fe9be-7f74-4a30-9044-50d7b92496fe">
I placed 'models' folder at the same folder of the jar. 
It the same for material.

I attached the full log : [log.txt](https://github.com/Dylancyclone/VMF2OBJ/files/12363729/log.txt)

I spend one hour one that. Any solution ? Caused by macOS ? 
Note : I used the Windows version of Portal from Steam (download from CrossOver and saved to my desktop). I extracted the .vmf from the /portal/maps/testchmb_a_00_d.bsp with 'bspsrc'

**Comment by Dylancyclone** [comment]
Hello!
Sorry about the long delay, life reared it's ugly head for a bit.

Portal is a mod for Half Life 2, and as such uses many resources from it. Next to the `portal` folder, there should be a `hl2` folder that contains all the content for Half Life 2.
`/Users/clogodfroy/Desktop/PortalExtract/Portal Files/hl2/hl2_misc_dir.vpk`
`/Users/clogodfroy/Desktop/PortalExtract/Portal Files/hl2/hl2_textures_dir.vpk`
These should be the source for most if not all of your missing files (like nodraw etc). Also, if you have extra materials and models, make sure you add them to the list of resources by clicking "Add Folder" and selecting the folder that contains the "models" and "materials" folders.

Let me know if that works!

**Comment by RetroAndDev** [comment]
Oh thats why !
I managed to convert the map with another tool. Effectively, I know that escapes maps needs HL2 textures and models.
My project is currently paused with Portal. But I don't think after to add HF2 ressources, in my mind it automatically got it, the logs are not precise from what game assets are missing. 
But thank you, I will try to check if that was that or not

**Comment by Dylancyclone** [comment]
Awesome!
And yep, there is a lot I could improve with this project, I hope I can find the time to make it easier to use.
I'm curious, what tool worked for you?

**Comment by RetroAndDev** [comment]
It was an Blender Add-on with GoldSrc and Source1. I don't have access to my computer now and I dont remind the name. I will check out when I have some extra time and retry this time with HL2 textures+models
