### ISSUE TITLE
Error when exporting map from the stanley parable to obj

### ISSUE THREAD

**Issue by JS101dotgit** [Dylancyclone/VMF2OBJ#48]
[1/5] Reading VPK file(s) and custom content...
SEVERE: Fatal error: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 10

**Comment by Dylancyclone** [comment]
Hi! Sorry about the delay, which map are you trying to convert?

**Comment by Junior-Michael** [comment]
map1

**Comment by Dylancyclone** [comment]
Hi!
I am unable to replicate this on the latest version, so I believe it might be fixed. Lemme know if you have any other issues
![image](https://github.com/Dylancyclone/VMF2OBJ/assets/19830705/6377af6a-53c9-4428-9335-ec8faff688a6)
