### ISSUE TITLE
VMF2OBJ returning empty OBJ

### ISSUE THREAD

**Issue by Jackseno** [Dylancyclone/VMF2OBJ#49]
Trying to convert some old Gmod maps to OBJ - Stripped out all ents, just brushes left. No fatal errors returned - The OBJ I'm getting is only empty verts?

![image](https://github.com/Dylancyclone/VMF2OBJ/assets/8571209/b8374f8c-1e69-419b-9904-26041d668438)

Is this a common problem? Apologies if I'm missing something obvious

edit; fixed by stripping the original VMF of all its textures - not an ideal solution but I didn't need them in this instance

**Comment by Dylancyclone** [comment]
Hi sorry about the delay, what map are you trying to convert?

**Comment by Dylancyclone** [comment]
Hi I'm going to close this since I don't have enough information to investigate further. Feel free to respond or create a new issue if you're still having trouble.
